### ISSUE TITLE
Child tasks screen doesnt adjust to my screen, and I cant scroll

### ISSUE THREAD

**Issue by paulvaden** [Pug-Life-INFO-461/allowance-gamification-app#172]
As you can see, the bottom buttons are cut off, and I am not able to scroll.  Resolution is 1920x1080 and 100% zoom.

<img width="952" alt="capture" src="https://user-images.githubusercontent.com/24904465/40900737-e4084f82-6781-11e8-9f72-67c6b3996549.PNG">

**Comment by Kidusyohanes** [comment]
In order to run the app as intended: 
Users must use Google Chrome browser on a computer
Users must use the incognito mode for each user
Users must open developer tools, and toggle the mobile view
Select the iPhone 6,7,8 option
Users must interact with the app interface only, i.e. users may not alter the URL for navigation
