### ISSUE TITLE
copied and pasted a weburl from my profile but it gave a different website with a task

### ISSUE THREAD

**Issue by harrybarng** [Pug-Life-INFO-461/allowance-gamification-app#178]
my family tab: 
![image](https://user-images.githubusercontent.com/37923379/40906076-99171ebe-6794-11e8-9878-dfd521d64266.png)

I copied and pasted: https://pug-life-55e2e.firebaseapp.com/parent-tasks.html

and it gave me 
![image](https://user-images.githubusercontent.com/37923379/40906103-aab4e840-6794-11e8-98af-77fbac6a2b03.png)

also copy and paste does not ask for any credentials

**Comment by 5tigerjelly** [comment]
In the actual application, users will not have access to the URL

**Comment by 5tigerjelly** [comment]
@abegel No, we had a short discussion about this during class a few weeks ago. We created it web-based, but it was intended to be packaged into a native iOS or Android application. 

However the issue is, we must register the apple developer account like TuBu did, which requires a $100 fee. The only reason they did it, was because one of their teammates already had a personal account with a developer account. 

For the sake of make the process simpler, we are showcasing the web view.
